

APP_VERSION ?= 0.1.0-snapshot
HELM_VERSION ?= 0.1.0-snapshot

DOCKER_TAG=${APP_VERSION}

IMG ?= quay.io/kubosa/exec/kindex:${DOCKER_TAG}
HELM_DOCKER_REPO := quay.io/kubosa/charts




BUILD_TS ?= $(shell date -u +%Y%m%d.%H%M%S)
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker



.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: version
version: ## Set version in binary
	@echo "// Generated by Makefile\n\npackage global\n\nvar Version = \"$(APP_VERSION)\"\nvar BuildTs = \"$(BUILD_TS)\"\n" >internal/global/version_.go


##@ Build

.PHONY: build
build: ## Build binary.
	CGO_ENABLED=0 go build -o bin/kindex main.go



##@ Docker

.PHONY: docker
docker: version docker-build docker-push  ## Build controller docker image and push

.PHONY: docker-build
docker-build: version ## Build docker image
	$(CONTAINER_TOOL) build -t ${IMG} .

.PHONY: docker-push
docker-push: ## Push docker image
	$(CONTAINER_TOOL) push ${IMG}


##@ Helm



define CHART_YAML
# File generated by Makefile
apiVersion: v2
name: kindex
version: $(HELM_VERSION)
appVersion: $(APP_VERSION)
description: "Very simple test server"
endef
export CHART_YAML

.PHONY: chart-yaml
chart-yaml: ## Generate the helm/kindex/Chart.yaml
	echo "$$CHART_YAML" >./helm/kindex/Chart.yaml

.PHONY: chart
chart: chart-yaml  ## Build and push helm chart
	cd ./helm && helm package -d ./../tmp kindex && helm push ./../tmp/kindex-${HELM_VERSION}.tgz oci://${HELM_DOCKER_REPO}


