
# RBAC: list Ingresses in all namespaces (required for the default in-cluster client).
rbac:
  create: true
  # clusterRoleName: ""
  # clusterRoleBindingName: ""

serviceAccount:
  create: true
  # name: ""

log:
  mode: "text"
  level: "INFO"



image:
  pullSecrets: []
  pullPolicy: IfNotPresent
  repository: quay.io/kubosa/exec/kindex
  # -- Overrides the image tag whose default is the chart appVersion.
  tag:



ingress:
  enabled: true
  host: # TBD
  class: # TBD
  networkPolicy:
    enabled: false
  annotations:
    kindex.kubotal.io/link: ""    # Hide ourselves
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # haproxy.org/ssl-passthrough: "true"
    # ingress.kubernetes.io/ssl-passthrough: "true""

server:
  tls: false
  extraHosts: [] # If TLS: fqdn added in certificate
  certificateIssuer: # TBD if ssl:true
  issuerKind: ClusterIssuer   # Or Issuer
  mode: dark
  clusterName: # TBD
  # No obvious reason to change the following
  bindAddr: "0.0.0.0"
  bindPort: 7788
  certDir: /cert/server
  certName: tls.crt
  keyName: tls.key
  dumpExchanges: 0

# NodeSelector for the pod to be installed
nodeSelector: {}
# -- Tolerations for the pod to be installed
tolerations: []

podSecurityContext:
  # runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - "ALL"

commonAnnotations: []

podAnnotations: []


extraVolumes: []
#   - name:
#     mountPath:
#     claimName:

resources:
  limits:
    memory: 500Mi
    cpu: "0.4"
  requests:
    memory: 500Mi
    cpu: "0.2"


# To allow overriding. But default should be OK
baseNameOverride:
certificateName:
certificateSecretName:
serviceName:
ingressName:
networkPolicyName:
serviceAccountName:
clusterRoleName:
clusterRoleBindingName: